### ISSUE TITLE
Scaffold FIL

### ISSUE THREAD

**Issue by xBalbinus** [filecoin-project/fil-b#21]
```[tasklist]
### Tasks
- [x] Create Frontend for Starter Kits
- [x] Start Examples Repo, consolidate existing use-cases into one repo (don't start a new repo for each starter kit, instead locate them on branches)
- [x] Library for Commonly Used Frontend Components
- [x] Upgrade dependencies
- [x] Replace inactive Filecoin faucet link in README https://github.com/filecoin-project/fevm-hardhat-kit?tab=readme-ov-file#fund-the-deployer-address
```

THE ABOVE TASK LIST IS OUTDATED.

https://github.com/filecoin-project/fevm-hardhat-kit
https://github.com/filecoin-project/raas-starter-kit
https://github.com/filecoin-project/state-storage-starter-kit
https://github.com/filecoin-project/fvm-starter-kit-deal-making
https://github.com/filecoin-project/fevm-foundry-kit

**Comment by trruckerfling** [comment]
Shared to Jarrod from Dev Guild

**Comment by jbarnes850** [comment]
@xBalbinus @trruckerfling thanks for sharing this! Here's a short plan and draft proposal to tackle these issues: https://docs.google.com/document/d/1LZ6dsmYjcTJdUIwO3G5sggXceNf1b-2bXcVELkH6vhM/edit?usp=sharing

Very open to any and all feedback!
