### ISSUE TITLE
Onchain payment PoC

### ISSUE THREAD

**Issue by longfeiWan9** [filecoin-project/fil-b#7]
## Overview
Onchain token payment PoC to demonstrate end-to-end how to use FIl or ERC20 tokens as payment on Filecoin for any services built on top of Filecoin, including storage service, computation service, DeFi service, or SP onboarding service. etc.

## Deliverables
Git repo which can be shared with potential partners to use. 
 - [OnchainPayment repor](https://github.com/FIL-Builders/OnchainPayment)
```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-project/fil-b/issues/6
- [ ] https://github.com/filecoin-project/fil-b/issues/8
- [ ] https://github.com/filecoin-project/fil-b/issues/11
- [ ] https://github.com/filecoin-project/fil-b/issues/12
- [ ] https://github.com/filecoin-project/fil-b/issues/9
- [ ] https://github.com/filecoin-project/fil-b/issues/10
```
